#!/bin/bash

# herbstluftwm config file.
# by Ian Taylor

hc() {
    herbstclient "$@"
}

notify-send --expire-time=5000 "Welcome back," "$USER@$HOSTNAME"

hc emit_hook reload

compton --opengl --vsync opengl-swc --paint-on-overlay -e.45 -f -D 6 -l-13 -t-13 -cCz -o 0.25 -b
feh --bg-fill $HOME/bin/wallpapers/2.jpg

killall stalonetray
hc rule class~'[Ss]talonetray' manage=off

# remove all existing keybindings
hc keyunbind --all

# keybindings
arrows=false	# add arrow key keybinding equivalents along with homerow
# if you have a super key you will be much happier with Mod set to Mod4
Mod=Mod1    # Use alt as the main modifier
#Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-e quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-q close
hc keybind $Mod-Return spawn urxvt

# application shortcuts
hc keybind $Mod-d				spawn dmenu_run -i -b
hc keybind $Mod-Shift-w			spawn firefox
hc keybind $Mod-Shift-Return	spawn thunar

# misc. shortcuts
hc keybind $Mod-Control-Delete	spawn systemctl suspend

# basic movement
# focusing clients
if [ "$arrows" = true ]; then
	hc keybind $Mod-Left  focus left
	hc keybind $Mod-Down  focus down
	hc keybind $Mod-Up    focus up
	hc keybind $Mod-Right focus right
fi
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
if [ "$arrows" = true ]; then
	hc keybind $Mod-Shift-Left  shift left
	hc keybind $Mod-Shift-Down  shift down
	hc keybind $Mod-Shift-Up    shift up
	hc keybind $Mod-Shift-Right shift right
fi
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode
# rotate a frame
hc keybind $Mod-e	chain .-. lock .-. rotate .-. rotate .-. rotate .-. unlock 
# cycle through frame layouts
hc keybind $Mod-space	chain , cycle_layout 1 , spawn $HOME/.config/herbstluftwm/notify-layout.sh

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
if [ "$arrows" = true ]; then
	hc keybind $Mod-Control-Left    resize left +$resizestep
	hc keybind $Mod-Control-Down    resize down +$resizestep
	hc keybind $Mod-Control-Up      resize up +$resizestep
	hc keybind $Mod-Control-Right   resize right +$resizestep
fi

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-Shift-period move_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible
hc keybind $Mod-Shift-comma  move_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-Shift-i jumpto urgent
hc set focus_follows_mouse 1

# theme
# dark: #113630
# lite: #c7f1a9
frame_all='#101010'
win_normal='#c7f1a9'
win_active='#113630'
hc set frame_border_active_color "$frame_all"
hc set frame_border_normal_color "$frame_all"
hc set frame_active_opacity 055
hc set frame_normal_opacity 000
hc set frame_border_width 2
hc set window_border_width 6
hc set window_border_inner_width 0
hc set window_border_normal_color "$win_normal"
hc set window_border_active_color "$win_active"
hc set always_show_frame 0
hc set frame_bg_transparent 255
hc set frame_transparent_width 0
hc set frame_gap 0
# add overlapping window borders
hc set window_gap 10
hc set frame_padding 0
hc set frame_gap 05
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done

# system tray
sleep 1 && stalonetray --geometry 1x1-10 --icon-gravity W --grow-gravity NE --icon-size 16 --kludges force_icons_size & 
ps cax | grep nm-applet > /dev/null
if [ $? -ne 0 ]; then
	nm-applet &
	menutray &
fi
